import React from 'react';
import EventItem from '../components/EventItem'; // Re-use EventItem for consistency

// PUBLIC_INTERFACE
function NotificationsPage() {
  /**
   * Displays a historical log of all notifications and alerts generated by the system.
   * Features a prominent header with an icon and title.
   * Uses the EventItem component to list notifications.
   */
  return (
    <div className="page-container">
      <header className="page-header">
        <span className="page-icon">🔔</span>
        <h1 className="page-title-text">Notifications & Alerts</h1>
      </header>
      <p>
        Review all past notifications, alerts, and helpful tips. This log helps
        you stay informed about important events related to Charlie's well-being
        and nursery environment.
      </p>

      <div className="card" style={{ marginTop: 'var(--spacing-md)' }}> {/* Consistent card styling */}
        <h2 style={{ marginBottom: 'var(--spacing-sm)', fontSize: '1.375rem' }}>Notification History</h2>
        <EventItem
            type="alert"
            icon="🌡️"
            message="Room temperature was high (25°C)."
            details="Occurred yesterday. Please ensure the room is comfortable."
            timestamp="Yesterday, 3:00 PM"
        />
        <EventItem
            type="tip"
            icon="💡"
            message="Remember to check diaper supplies."
            details="Low stock detected by smart nursery (conceptual feature)."
            timestamp="2 days ago"
        />
         <EventItem
            type="log"
            icon="🩺" // Using a stethoscope for health related log
            message="Health check-up reminder."
            details="Dr. Smith, appointment scheduled for next week."
            timestamp="3 days ago"
        />
        <EventItem
            type="alert"
            icon="😢" // Crying face for sound alert
            message="Crying detected for over 5 minutes."
            details="Baby may need immediate attention."
            timestamp="4 days ago, 10:15 AM"
        />
      </div>
    </div>
  );
}

export default NotificationsPage;
